name: Packaging

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  wheels:
    name: Build ${{ matrix.os }} wheels
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04,macos-12]

    env:
      CIBW_SKIP: "cp27-* cp36-* cp37-* pp* *-win32 *-manylinux_i686 *-musllinux_*"
      CIBW_BEFORE_ALL: >
        pip install cmake>=3.5 &&
        (if [ "$(uname)" == "Linux" ]; then yum install -y devtoolset-10-libatomic-devel; fi)
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install cibuildwheel
      run: python -m pip install cibuildwheel
    - name: Build wheels
      run: python -m cibuildwheel --output-dir wheelhouse
    - uses: actions/upload-artifact@master
      with:
        name: wheelhouse-${{ matrix.os }}
        path: wheelhouse
